// JOKES
const jokes = [
    "Your Mom.",
    "Your Dad.",
    "Your Face.",
    ["Why can't women ski?", "Because there's no snow in the kitchen."],
    ["How do you get a nun pregnant?", "Dress her up like the alter boy."],
    ["What is the difference between a Joke and Two Dicks?", "You can't take a joke."],
    ["What is the skeletons favorite meal?", "Ribs."],
    ["How do you catch a polar bear?", "Cut a hole in the ice, and Kick Him in the IceHole!"],
    ["What do you get if you mix an Elephant and a Rhino?", "elephino."],
    ["Schroding gets pulled over by a cop. The cop searches his car to find a box in the trunk.\nThe cop says, \"Mr. Schrodinger, you know there's a Cat in here?\"", "Schrodinger says, \"I do now!\""],
    ["I'm reading a book on anti-gravity,", "I can't seem to put it down."],
    ["What do you gett when you cross an octopus with a cow?", "Your research grant revoked."],
    "A scientist goes to shoot a deer and misses 5 feet to the left.\nA politician then shoots at the deer and misses 5 feet to thr right. \n The statician yells, \"We got em!\"",
    ["What do we want?\nEQUAL RIGHTS FOR BIPOLAR PEOPLE!\nWhen do we want it?!", "nevermind."],
    ["There is a disease you can get from Linux", "It's terminal."],
    ["I think I should donate some money to Red Hat.", "*tips Fedora*"],
    ["How many Windows engineers does it take to change a lightbulb?", "None. They just change the standard to darkness."],
    ["Why do Vampires use Linux?", "Because they don't want any Windows in their house."],
    ["Why do Hackers take Xanax?", "Because they have a lot of daemons."],
    "Debian seems to have a very Apt package manager.",
    ["What are clouds made of?", "Linux."],
    ["Why do astronauts use Linux?", "Because you can't open Windows in space."],
    ["How many Political Idealists does it take to change a lightbulb?", "None. Political idealists don't change anything."],
    ["Why does the Polically Correct Soccer team always lose?", "Because, No Offense."],
    ["Why did the Police Chief tell his officers to show up 15 Minutes early?", "to beat the crowds."],
    ["Where would Martin Luther King be if he wasn't black?", "Alive."],
    ["What's the difference between a Hooker and an Onion?", "I cry when I cut up an onion."],
    ["Why did Steven Hawking do One-Liners?", "Because he can't do Stand-Up."],
    ["What does NVidia and Women have in common", "Horrible Drivers."],
    ["My girlfriend calls me a paedophile", "Big words for a 10 year old!"],
    ["How do you get all of the Mexicans in Mexico into one place?", "Roll a Quarter down the street."],
    ["Why do Mexicans have low-riders?", "So they can pick up change while going down the street."],
    "Who would win a fight between a Gorilla and a Dickfor?",
    ["The biggest knight at King Arthur's round table was Sir Cumference.", "He acquired his size from eating too much pi."]];

//FACTS
const facts = [
    "A straw only has one hole in it.",
    "The word Mercedes has 3 E's in it, all pronounced differently.",
    "The first person caught speeding was going 8 miles per hour.",
    "A Sea Slug can have its head cut off, and grow a new body.",
    "The heads on Easter Island have bodies beneath the surface.",
    "The Moon has Moonquakes.",
    "A Wood Frog can hold its pee for up to 8 months.",
    "Libya is the hottest spot on the planet with recorded temperatures of up to 136F.",
    "You typically only breathe out of one nostril at a time.",
    "Vegetables don't actually exist outside of cullinary arts.",
    "Your brain uses around 20% of your body's oxygen and blood.",
    "Humans are only born with 2 natural fears: \nThe fear of falling (basiphobia), and the fear of loud noises (phonophobia).",
    "8% of your body weight comes from your blood, while another 16% comes from your skin.",
    "Ancient Greece and Ancient Rome didn't have the number 0.",
    "Caesar Salad was invented in Mexico by an Italian-American.",
    "Squirrels cause most of the power outages in the U.S.",
    "Children of Identical-Twins share enough DNA to be considered Siblings, not cousins.",
    "March 3rd is \"What If Cats and Dogs Had Opposable Thumbs Day.\"",
    "Cruise ships have their own morgues.",
    "Humans and the Tree Shrew are the only two mammals that enjoy spicy food.",
    "Lady Bugs defend themselves by bleeding from their knees.",
    "The worlds smallest McDonald's was designed for Honey Bees.",
    "'Chocolate' is 'Cocoa'. \n'Blossom' is 'Bloom'. \n'Masculine' is 'Male'. \n'Deceased' is 'Dead'",
    "Astronauts can bake cookies in space.",
    "The inventor of the pringles can is buried in one.",
    "Bubble wrap was originally intended to be wallpaper.",
    "3 Musketeers were originally in packs of 3, with 3 different flavors: \nVanilla, Chocolate, and Strawberry.",
    "The U.S. Navy uses Xbox 360 controllers for Parascopes on Submarines.",
    "Charlie Chaplin once lost a Charlie Chaplin look-alike competition.",
    "There is an Ant that exists on the 14-Block in Manhattan that exists nowhere else on earth. The ManhattAnt.",
    "The human body has been proven to emit light by Japanese researchers.",
    "Copper door knobs are self-disinfecting.",
    "Cotton candy was invented by a dentist.",
    "The word 'set' has the largest number of meanings in the english language.",
    "One of the first computer, ENAIC, was built in 1946 and weighed 60,000 pounds.",
    "Space allegedly smells like hot metal or burnt steak.",
    "Bees have been known to sting other bees.",
    "E is the most common letter, appearing in 11% of words.",
    "A dozen bodies were found in Benjamin Franklin's basement, 6 of which were children.",
    "Panama is considered the healthiest place to live.",
    "Some people have an extra bone in their knee called a fabella.\nIn 1918 only 11% of people had this bone. In 2018 39% of have this 'new' bone.",
    "Pringles are not technically potato chips. Nowhere on the package says Chips because they are pressed into shape from dehydrated potato flakes.",
    "Dolphins were trained for war by the U.S. and the Soviet Union during Vietnam and the Cold War.",
    "Less than 20% of Laughter comes from hearing jokes.",
    "There is enough Iron in the blood to be turned into a 3\" nail.",
    "Koalas have fingerprints.",
    "Humans are 1 of 8.7 millions species that live on earth.",
    "The first iPhone was made by Cisco, not Apple.",
    "Comic Sans font actually came from comic books, inspired by comics like Watchmen.",
    "Scotty from Star Trek stormed the beaches of Normandy as a lieutenant on D-Day.",
    "Apples come from Asia. Pies come from Midieval Europe. Putting Apples in Pies traces back to England. \n\"As American as Apple Pie\" is inaccurate.",
    "\"When In Rome, Do as the Romans Do\" comes from a Roman phrase that actually said \"To be a Roman, Act like a Roman\" which was Alexander the Greats way of convincing other nations to join his Alliance.",
    "Your sneeze faster than a cheetah runs, and 20 times faster than Michael Phelps swims.",
    "The patent for the fire hydrant was lost in a fire.",
    "Pluto was discovered in 1930. Taking 248 Earth-years to orbit the Sun, Pluto is not even one year old.",
    "Cows are more deadly to humans than sharks are.",
    "Your liver can regrow itself in 3 weeks.",
    "Dogs like squeaky toys because it sounds like a small animal dying.",
    "The founder of Atari is also the creator of Chuck E. Cheese.",
    "Crows hold grudges.",
    "The earliest computers were punch-card computers invented to help with the census.",
    "The first computer mouse was made out of wood in 1964.",
    "The Sasser worm targets Windows by exploiting a vulnerable network port, and then deletes itself after infecting the system to make tracing difficult.",
    "Microsoft, Apple and H.P. all started from a garage.",
    "Roughly 5,000 new computer viruses are created every month.",
    "The first message sent over the internet, in 1969, was 'lo'. This is because the word 'login' crashed the internet before the message finished.",
    "Only 10% of the worlds money exists physically.",
    "For a computer to be equivalent to the human brain, it would need to process 38 thousand-trillion operations a second and store 3.5 petabytes of memories.",
    "Humans blink 20 times a minute on average, but only 7 times a minute when looking at a computer.",
    "The first Gigabyte disk was made in 1980, weighing 550 pounds and cost $40,000.",
    "The first computer programmer was a woman.",
    "MyDoom was the most expensive computer virus in history, causing $38 billion in damage.",
    "CAPTCHA means Completely Automated Public Turing Test to Tell Cumputers and Humans Apart.",
    "Research says 123456 and 12345678 are the most common passwords in the world.",
    "The term 'bug' came from a moth that caused a malfunction in the Mark II computer. Computer Scientists then coined the term bug and debug.",
    "The Creeper was the first computer virus, built as a harmless test to study PDP-10 computers on ARPAnet."
]

exports.joker = jokes;
exports.facter = facts;
